### ISSUE TITLE
Undefined is not a function in components

### ISSUE THREAD

**Issue by maconley** [gcanti/tcomb-form#281]
Hello,

I am using the most current versions of both `tcomb-form` and `React`. When attempting to render a form, I get the following error:

````
TypeError: undefined is not a function
    at Textbox.render (/node_modules/tcomb-form/lib/components.js:303:16)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/node_modules/react/lib/ReactCompositeComponent.js:587:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/node_modules/react/lib/ReactCompositeComponent.js:607:32)
    at [object Object].wrapper [as _renderValidatedComponent] (/node_modules/react/lib/ReactPerf.js:66:21)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/node_modules/react/lib/ReactCompositeComponent.js:220:30)
    at [object Object].wrapper [as mountComponent] (/node_modules/react/lib/ReactPerf.js:66:21)
    at Object.ReactReconciler.mountComponent (/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/node_modules/react/lib/ReactMultiChild.js:241:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/node_modules/react/lib/ReactDOMComponent.js:592:32)
    at ReactDOMComponent.Mixin.mountComponent (/node_modules/react/lib/ReactDOMComponent.js:482:29)
    at Object.ReactReconciler.mountComponent (/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/node_modules/react/lib/ReactMultiChild.js:241:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/node_modules/react/lib/ReactDOMComponent.js:592:32)
    at ReactDOMComponent.Mixin.mountComponent (/node_modules/react/lib/ReactDOMComponent.js:482:29)
    at Object.ReactReconciler.mountComponent (/node_modules/react/lib/ReactReconciler.js:37:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/node_modules/react/lib/ReactCompositeComponent.js:225:34)
    at [object Object].wrapper [as mountComponent] (/node_modules/react/lib/ReactPerf.js:66:21)
    at Object.ReactReconciler.mountComponent (/node_modules/react/lib/ReactReconciler.js:37:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/node_modules/react/lib/ReactCompositeComponent.js:225:34)
    at [object Object].wrapper [as mountComponent] (/node_modules/react/lib/ReactPerf.js:66:21)
    at Object.ReactReconciler.mountComponent (/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/node_modules/react/lib/ReactMultiChild.js:241:44)
````
I started with a more complex form with a model, but when I got this error, I tried simply copying the working example with the `Person` struct from the guide to make sure it wasn't an issue with the form I built. However I still got the same error. It only says `Textbox` above since that happened to be the first item in the form; every form input type has the same issue.

The line in question (303) is:

`var vdom = template(locals);`

**Comment by gcanti** [comment]
Hi, 

That is weird. Just made a test with a fresh setup:

- react v0.14.5
- react-dom v0.14.5
- tcomb-form v0.7.10

This is the code:

```js
import React from 'react'
import t from 'tcomb-form'
import { render } from 'react-dom'

const Type = t.struct({
  name: t.String
})

class App extends React.Component {

  render() {
    return <t.form.Form type={Type} />
  }

}

render(<App />, document.getElementById('app'))
```

and it works fine. Any clue on what's wrong?

**Comment by gcanti** [comment]
Closing for inactivity, feel free to reopen.
